app/App_Resources/Android/app.gradle, app/main-page.ts, app/main-page.xml, app/main-view-model.ts, app/pages/basics.xml, app/pages/buttons-vm.ts, app/pages/buttons.ts, app/pages/buttons.xml, app/pages/sidedrawer.xml, app/pages/themes.xml, app/scss/_action-bar.scss, app/scss/_index.scss, app/scss/_labels.scss, app/scss/_layouts.scss, app/scss/_list-view.scss, app/scss/_segmented-bar.scss, app/scss/_slider.scss, app/scss/_stack-layout.scss, app/scss/_switch.scss, app/scss/_variables.scss, app/scss/themes/core/_variables_dark.scss, app/scss/themes/core/_variables_light.scss, app/scss/themes/core/platforms/_action-bar.android.scss, app/scss/themes/core/platforms/_app-common.scss, app/scss/themes/core/platforms/_buttons.android.scss, app/scss/themes/core/platforms/_buttons.ios.scss, app/scss/themes/core/platforms/_index.android.scss, app/scss/themes/core/platforms/_index.ios.scss, app/scss/themes/core/platforms/_labels.android.scss, package.json
https://github.com/NativeScript/theme/issues/18
https://github.com/NativeScript/theme/issues/17
https://github.com/NativeScript/theme/issues/16
Provides a lot of base level variables and classes, including base label classes for both iOS and Android per the spec.
=> feat: base color variables, label classes, and beginning actionbar

app/pages/buttons.xml, app/scss/_buttons.scss, app/scss/_variables.scss, app/scss/mixins/_buttons.scss, app/scss/themes/core/_buttons.scss, app/scss/themes/core/platforms/_button.android.scss, app/scss/themes/core/platforms/_button.ios.scss, app/scss/themes/core/platforms/_index.android.scss, app/scss/themes/core/platforms/_index.ios.scss
Button styles, I wouldn't consider this a final version, but any feed back would be appreciated
=> Button styles

README.md, app/pages/progress.ts, app/pages/progress.xml, app/scss/_activity-indicator.scss, app/scss/_index.scss, app/scss/_progress.scss, app/scss/_variables.scss
=> Add Progress\Activity styles, update readme

app/scss/_buttons.scss, app/scss/_variables.scss
`$btn-colo-outline-highlighted` renamed to:
`$btn-color-outline-highlighted`
=> FIX: variable name typo

package.json
=> Add node-sass dev-dependency

scripts/builder.js, scripts/postinstall.js
=> Updated build and postinstall scripts for new SCSS locations 

app/theme-core-scss/themes/core/platforms/_buttons.android.scss
Should resolve #94 - the Android ripple/ink effect that doesn't work currently.
=> Fix Android Button Ripple

scripts/postinstall.js
Fixes the install issue on Mac's
=> Fix TNS bug on mac

.eslintignore, .eslintrc.js, .gitignore, .travis.yml, scripts/builder.js, scripts/postinstall.js, scripts/travis/lint.sh, scripts/uninstall.js
- Add eslint configs and travis `before_install` hook for linting.
- Fix code style errors to follow the NativeScript coding conventions.
=> Style(eslint): add CI linting, fix code style errors

scripts/postinstall.js
Fixes the Name of the function to CheckIfTempInstall
=> This renames the function to checkIfTempInstall

.gitignore, app/app-root.xml, app/app.ts, app/main-page.xml, app/pages/base.ts, app/pages/basics.xml, app/pages/buttons-active.xml, app/pages/buttons.xml, app/pages/colors.xml, app/pages/dialogs.xml, app/pages/forms.xml, app/pages/listview.xml, app/pages/progress.xml, app/pages/search.xml, app/pages/segmentbar.xml, app/pages/sliders.xml, app/pages/switches.xml, app/pages/tabs.xml, app/pages/themes.ts, app/pages/themes.xml, app/theme-support/index.js, package.json, tsconfig.json
This PR contains the tasks mentioned in #147 
Let's not merge this until this PR gets merged
https://github.com/NativeScript/NativeScript/pull/6124
=> Upgrade Project to {N} 4.x

app/actionBar/actionBar.ts, app/app.ts, app/main-page.ts, app/navigation-vm.ts, app/pages/base.ts, app/pages/basics.ts, app/pages/buttons-active.ts, app/pages/buttons.ts, app/pages/colors.ts, app/pages/dialogs.ts, app/pages/forms.ts, app/pages/listview.ts, app/pages/login-form.ts, app/pages/login-landing.ts, app/pages/modal.ts, app/pages/progress.ts, app/pages/search.ts, app/pages/segmentbar.ts, app/pages/sliders.ts, app/pages/switches.ts, app/pages/tabs.ts, app/pages/themes.ts, app/scss/platforms/_action-bar.android.scss, app/scss/platforms/_buttons.android.scss, app/sidedrawer/sidedrawer.ts, app/sidedrawer/sidedrawer.xml, app/theme-support/index.js, nativescript-theme-core.json, package.json
https://github.com/NativeScript/NativeScript/pull/7055#issuecomment-482074141 introduced a regression for the styling of outline buttons in Android. 
We are leveraging the new `androidElevation` property introduced with https://github.com/NativeScript/NativeScript/pull/7136 to address this theming issue.
=> fix(android): outline button styling

.travis.yml, README.md, app-compat/app.js, app-compat/app.scss, app-compat/pages/themes.js, app/app.js, app/app.scss, app/bootstrap-based.scss, app/customized.scss, app/kendo-bootstrap.scss, app/kendo-default.scss, app/kendo-material.scss, app/pages/themes.js, package-lock.json, package.json, scripts/builder.js, src/package.json, webpack.config.js
Transform `nativescript-theme-core` to `@nativescript/theme` (scoped) package.
=> feat: scoped package

src/scss/variables/_blue.scss
Update "blue" accent color to match the templates' design.
=> fix(blue-skin): update accent color

src/scss/core/primitives/_index.scss, src/scss/mixins/_colorize.scss
Add `.ns-modal` root classes and generate default styles for it.
Implements a part of: https://github.com/NativeScript/theme/issues/194.
=> feat(modal): add default styles for modals

src/scss/core/primitives/_index.scss, src/scss/mixins/_colorize.scss
Cherry-pick https://github.com/NativeScript/theme/pull/224 only to release as v2.2.1
=> feat(modal): add default styles (#224)

MIGRATION-GUIDE.md
=> docs: make the custom index import note more visible

README.md
=> docs: Remove beta mentions

.eslintrc, CHANGELOG.md, README.md, package.json, src/index.d.ts, src/index.js, webpack.config.js
- Theme.Light/Theme.Dark/Theme.Auto are the available modes now.
- Hard mode changes are not affected by system mode changes, the default mode is Theme.Auto
- toggleMode now takes into account systemAppearance to decide the alternate mode (6.2+)
=> feat(mode): Add support for hard changing the mode in {N} 6.2+

package.json, src/index.js
Fixes https://github.com/NativeScript/theme/issues/231 + package version bump
=> fix: root check

.gitignore, package.json, references.d.ts, scripts/builder.js, src/index.js, tsconfig.json, webpack.config.js
es2017 build of theme for {N} 7
=> chore: dep updates

.github/PULL_REQUEST_TEMPLATE.md
PR Templates have links to 404.
PR Template links go to the right place
=> docs(PULL_REQUEST_TEMPLATE): Fixes 404s in PR Template
