package.json
Ping @NathanWalker.
Just an fyi that I needed to add “glob” as a devDependency to get this up and running.
=> Adding glob as a devDependency

app/pages/basics.xml, app/scss/_button.scss, app/scss/_variables.scss, app/scss/mixins/_buttons.scss
Using mixin of btn-base wanted to see everyone’s thoughts about this. it looks good in IOS. 
Update: I end up fixing button size inconsistencies, by setting the button border width. however, we may still want to look into using platform specific css or https://www.npmjs.com/package/nativescript-platform-css.
Android:
iOS:
=> Buttons base

README.md
`run` will launch new emulator for both iOS and Android if no device or emulator available.
=> run instead emulate

app/sidedrawer/sidedrawer.xml
Changed side drawer  buttons to labels and moved the tap event to the
wrapping gridLayout. This way the icon and the text are both tappable.
=> Side drawer button change 

app/_custom.scss, app/app.android.scss, app/bootstrap-based.android.scss, app/bootstrap-based.ios.scss, app/customized.android.scss, app/customized.ios.scss, app/pages/themes.ts, app/pages/themes.xml, app/scss/_bootstrap-map.scss, app/scss/_variables.scss, app/scss/themes/core/_dark.scss, app/scss/themes/core/_light.scss, app/scss/themes/core/_variables_dark.scss, app/scss/themes/core/_variables_light.scss, package.json
With this PR you should be able to customize the scss theme in the following ways:
In your `app.scss` file you can set the theme variables (or import another partial) before importing the theme file. [Example](https://github.com/NativeScript/theme/blob/allow-customizations/app/customized.android.scss#L8-L9)
This is useful **code share with Web project scenario**.
You reuse some of the styling form bootstrap theme (along with the cusomizations you have made on it). To do that - in your `app.scss`:
1. _(Optional)_ Import you `_custom.scss` with customization of bootstrap variables. This will be the way to [customize the bootstrap theme](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L3-L4).
1.  Import `varialbes.scss` from the bootstrap theme. If installed with `npm` you …
=> Allow scss theme customizations

scripts/builder.js, scripts/postinstall.js, scripts/uninstall.js
- The theme is now appended instead of added in the beginning of the file
- The app.css file is created if not existing
- Removed trailing whitespace and tabs
=> fix(js): Append theme sheet to app.css

app/scss/_variables.scss
`inherit` CSS value is currently not supported in NativeScript. In the `3.0` release we will log and error about [inherit] value not being valid. Better just remove it for now.
=> The "inherit" value is currently not supported

app/scss/_switch.scss
This PR fixes a bug where the switch thumb was not grabbing the `$accent` color.
The next gif shows the issue. There, I change between css and scss themes. The scss themes render the switch thumb always in blue. 
This PR fixes that!
Thanks!
=> Fix switch thumb color when using scss.

src/scss/mixins/components/_button.scss, src/scss/variables/_index.scss
The `border-radius` property of the CSS class `button.-rounded-lg` is not applied when `.ns-ios`
=> Fix unapplied border-radius property

src/scss/mixins/components/_action-bar.scss
This adds padding to the action items on Android, so that they are not cluttered to each other.
=> fix: add more padding to action items

.gitignore, src/scss/core/_controls.scss, src/scss/mixins/components/_controls.scss
Preconditions:
- Android platform
- `Frame` as an application root view
According to the preconditions, there is a white screen blink when launching the application.
It is due to no background color definition for the Frame, so it results in showing a white screen before executing the navigation to the default page.
=> feat: add Frame control

app-compat/app.scss, app-compat/customized.compat.scss, app/app.scss, app/customized.scss, package-lock.json, package.json, src/_index.scss, src/default.compat.scss, src/default.scss, src/scss/_controls.scss, src/scss/core/_controls.scss, src/scss/core/_utilities.scss, src/scss/core/colors/_index.scss, src/scss/core/primitives/_bootstrap.scss, src/scss/mixins/components/_forms.scss, src/scss/mixins/components/_list-view.scss, src/scss/mixins/components/_side--drawer.scss, src/scss/variables/_blue.scss, src/scss/variables/_default.scss, src/scss/variables/_grey.scss, src/scss/variables/_index.scss
Make $focus only internal (though backwards compatible), $accent works again
Remove styling and CSS vars from Core to reduce the core file size
Add them in a new default skin
=> Fix accents, separate default core styling

scripts/builder.js
Generate pre-parsed JSON files for all CSS files in the theme.
All the JSON files can be registered by doing: `require("@nativescript/theme/register-json")`
The JSON files are not needed if webpack is configured to use `css2json` loader for CSS as it will do the same during webpack build.
=> feat: ship pre-parsed JSON files for all CSS

src/scss/_bootstrap.scss, src/scss/_controls.scss, src/scss/_index.scss, src/scss/core/primitives/_bootstrap.scss, src/scss/mixins/components/_forms.scss
Currently .text-primary and .nt-form__link classes are not dependent on skin colors, while they should be.
.text-primary and .nt-form__link classes change colors with the current skin.
Fixes #245.
=> fix: Bootstrap and .nt-form colors not adapting to skin

CHANGELOG.md, package.json, src/package.json, src/scss/core/colors/_index.scss
Using SASS with node-sass crashes the app due to broken compilation.
Compilation is fixes, app doesn't crash.
Fixes #234.
Libsass treats map keys as colors if they don't have quotes.
=> fix: CSS variables output with node-sass is causing crashes

CHANGELOG.md, package.json, src/package.json, src/scss/_bootstrap.scss, src/scss/mixins/_utilities.scss
Fix .bg-primary not set background after accent changes
Fixes/Implements/Closes #255.
=> fix: wrong ActionBar colors, introduced with node-sass fix in 2.3.2

src/index.js
Plugins aware of dark mode and using {N} way to get it are not following force mode changes.
Plugins are changing according to forced Theme mode.
Fixes #250.
=> fix: RadCalendar (and probably other plugins) not following forced mode changes

app/pages/forms.xml, package.json, src/scss/_controls.scss, src/scss/core/_controls.scss, src/scss/mixins/components/_forms.scss
Custom components based on TextField can't be styled as a TextField easily.
.nt-input class to style them.
Fixes #261.
BREAKING CHANGES:
* `.nt-input` class is now used for both inputs and input groups. The group top/bottom margin is removed and the whole group has the same margin as the TextField. The overall look is the same. Low impact - users most likely don't rely on the group margin at all.
=> fix: inputs don't provide styling for custom components.

app/pages/themes.js, app/pages/themes.xml, package.json, src/index.js, src/scss/mixins/components/_forms.scss
Fix a border-radius error in RDF
If the device is in dark mode, setting forced theme to light/dark and back to auto leaves the app in light mode.
The app is returned to the current device mode.
Fixes/Implements/Closes #265.
=> fix(system-theme): Make sure setting Theme to Auto applies the changes

src/index.js
Fixes #280 it looks like at some point this might have been changed from appCommon to Application and this reference missed.
#280 
Works as expected, calling `Theme.setMode(Theme.Auto)` resets to system's Dark Mode Setting.
Fixes #280.
=> Fixes Error "appCommon is not defined"

src/scss/mixins/_utilities.scss
Started trying to use this mixin then noticed a logic error.
The unit of `$size` will always be `(!em || !rem)` because if it's one it's not the other. Changed to `and` because I think that's the desired functionality? It looks like the fallback case is to strip the units off of the input value, seems a little strange, might need further discussion about what's actually going on here?
- Link is also a 404, please update this template.
- N/A. Feel free to open if it seems necessary.
- Link is also a 404, please update this template.
- Link is also a 404, please update this template.
`rem-to-dip` always returns the input size without units, for example:
```scss
// $font-size: 12;
// Functon call
font-size: rem-to-dip(1.7rem);
// Desired output
font-size: 20;
// Actual Output
font-size: 1.7; …
```
=> Fix rem-to-dip

CHANGELOG.md, package.json, scripts/builder.js, src/index.js, src/package.json
- setMode crashes do to some changes in the NS7 runtimes
- setMode doesn't change the theme properly
- setMode no longer crashes
- setMode changes the theme dynamically.
This has already been published as 2.3.4 - To fix a Internal Support Issue.
=> fix: NS6/7 setMode fixes
